# Copyright (C) 2026 boostsecurity.io
# SPDX-License-Identifier: AGPL-3.0-or-later

FROM cgr.dev/chainguard/wolfi-base:latest@sha256:9925d3017788558fa8f27e8bb160b791e56202b60c91fbcc5c867de3175986c8

RUN apk add --no-cache upx=5.1.1-r1

ENTRYPOINT ["/usr/bin/upx"]
