# Copyright (C) 2026 boostsecurity.io
# SPDX-License-Identifier: AGPL-3.0-or-later

QUICKSTART_RELEASE_VERSION :=
QUICKSTART_RELEASE_REGISTRY := ghcr.io/boostsecurityio
QUICKSTART_RELEASE_REPOSITORY := boostsecurityio/smokedmeat
QUICKSTART_KITCHEN_IMAGE_REF :=
QUICKSTART_CLOUD_SHELL_IMAGE_REF :=
QUICKSTART_COUNTER_DARWIN_ARM64_SHA256 :=
QUICKSTART_COUNTER_DARWIN_X86_64_SHA256 :=
QUICKSTART_COUNTER_LINUX_ARM64_SHA256 :=
QUICKSTART_COUNTER_LINUX_X86_64_SHA256 :=
QUICKSTART_COUNTER_WINDOWS_ARM64_SHA256 :=
QUICKSTART_COUNTER_WINDOWS_X86_64_SHA256 :=
